version: '3'

services:
  web:
    build: .
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=app
      - POSTGRES_PORT=5432
    ports:
      - "4000:4000"
    volumes:  
      - .:/app
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:11.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data